config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root to: redirect('/photos')
  resources :photos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Pour message alerte Bootstrap
  add_flash_types :success, :warning, :danger, :info
end

def self.helper_method(*); end
def self.helper(*); end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json

  # On ajoute une nouvelle photo
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, success: 'Photo créée.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json

  # On edite une photo existante
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, info: 'Photo mise à jour.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json

  # On supprime définitivement une photo de la db
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, danger: 'Photo supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :description, :file)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galerie Photos</title>
    <%= csrf_meta_tags %>
  	<!-- Latest compiled and minified CSS -->
    <%= stylesheet_link_tag href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" %>
  	<!-- Optional theme -->
    <%= stylesheet_link_tag href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
  </head>

  <body>
	 <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><i class="fa fa-camera-retro" aria-hidden="true"> Galerie Photos</i></a>
      </div>
    <!-- Navbar -->
    <p class="navbar-text navbar-right">
    <%= link_to 'À propos de', pages_info_path, class:'navbar-link' %></p>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
      	<!-- <li class="active"><a href="/photos">Photos</a></li> -->
        <li><%= link_to 'Ajouter une photo', new_photo_path %></li>
      </ul>
    </div>
    </div>
   </nav>
   <!-- end navbar -->

    <!-- Flash pour faire fonctionner les messages alertes de Bootstrap -->
  	<div class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    </div>

    <footer>
      <div class="container">
      &copy; Yannick G&#45;F. 2016-2017
      </div>
    </footer>

  <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/info.html.erb
<h1><em>À propos de</em></h1>
<br>
<p>Ressources principales pour la création de cette appli &#58;</p>
<%= link_to 'Railsgirls', asset_path("http://railspremierspas.humancoders.com/"), :target => "_blank" %><br>
<%= link_to 'Rails tutorial', asset_path("https://www.railstutorial.org/"), :target => "_blank" %><br>
<%= link_to 'Rails Guides', asset_path("http://edgeguides.rubyonrails.org/index.html"), :target => "_blank" %>

app/views/photos/_form.html.erb
<%= form_for(photo) do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titre %>
    <%= f.text_field :title, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :fichier %>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit class:'btn btn-primary', value: 'VALIDER'  %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1><em>Éditer les photos</em></h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Aperçu', @photo %> |
<%= link_to 'Retour', photos_path %>

app/views/photos/index.html.erb
<h1>Afficher les photos</h1>

<% @photos.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |photo| %>
      <div class="col-xs-4">
        <%= image_tag photo.file_url, :width => '100%' if photo.file.present?%>
        <h4><%= link_to photo.title, photo %></h4>
        <%= photo.description %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/new.html.erb
<h1>Nouvelle Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Retour', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-9">
    <%= image_tag(@photo.file_url, :width => "100%") if @photo.file.present? %>
  </div>

  <div class="col-xs-3">
    <p><b>Titre: </b><%= @photo.title%></p>
    <p><b>Description: </b><%= @photo.description %></p>
    <p>
      <%= link_to 'Editer', edit_photo_path(@photo) %> |
      <%= link_to 'Supprimer', @photo, confirm: 'Tu veux l/a supprimer définitivement?', method: :delete %> |
      <%= link_to 'Retour', photos_path %>
    </p>
  </div>
</div>